site_name: Dev-Corner
pages:
- Home: 'index.md'
- Installation: 'install.md'
- Data: 'data.md'
- Licenses: 'licenses.md'
- About: 'about.md'
theme: yeti
markdown_extensions:
    - fenced_code
    - smarty
